# Generated by Django 4.2.1 on 2023-05-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convite', models.ImageField(upload_to='convites')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='evento.inscricaoevento')),
            ],
            options={
                'verbose_name_plural': 'ConviteEvento',
            },
        ),
    ]
