# Generated by Django 4.2.1 on 2023-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_conviteevento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConviteEvento',
        ),
    ]
